#!/usr/bin/env bash
# One-shot: Coturn (TURN) + Laravel in-app call env for real-device WebRTC.
#
# Run on the server as root (after git pull on panun-admin dev branch):
#   cd /path/to/panun-admin   # Laravel root (where artisan lives)
#   sudo bash scripts/setup-in-app-call-turn.sh
#
# Optional: pass Laravel root as first argument.

set -euo pipefail

LARAVEL_ROOT="${1:-}"
if [[ -z "$LARAVEL_ROOT" ]]; then
  for p in \
    "/home/u397782854/domains/panunkaergar.com/dev" \
    "/home/u397782854/domains/panunkaergar.com/public_html/subdomains/dev" \
    "/var/www/panun-admin" \
    "/var/www/html" \
    "$(pwd)"; do
    if [[ -f "$p/artisan" ]]; then
      LARAVEL_ROOT="$p"
      break
    fi
  done
fi

if [[ -z "$LARAVEL_ROOT" ]] || [[ ! -f "$LARAVEL_ROOT/artisan" ]]; then
  echo "Error: Laravel root not found. Usage: sudo bash $0 /path/to/laravel"
  exit 1
fi

echo "==> Laravel root: $LARAVEL_ROOT"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Error: run as root (sudo bash $0)"
  exit 1
fi

export DEBIAN_FRONTEND=noninteractive
if command -v apt-get >/dev/null 2>&1; then
  apt-get update -qq
  apt-get install -y -qq coturn openssl curl
else
  echo "Error: apt-get not found. Install coturn manually, then re-run env section."
  exit 1
fi

TURN_USER="panun_turn"
TURN_SECRET="$(openssl rand -hex 24)"
PUBLIC_IP="$(curl -sS --max-time 5 https://api.ipify.org 2>/dev/null || curl -sS --max-time 5 https://ifconfig.me 2>/dev/null || true)"
PUBLIC_IP="${PUBLIC_IP:-187.127.135.66}"

echo "==> Using public IP for TURN: $PUBLIC_IP"

cat >/etc/turnserver.conf <<EOF
# Generated by scripts/setup-in-app-call-turn.sh
listening-port=3478
fingerprint
lt-cred-mech
user=${TURN_USER}:${TURN_SECRET}
no-multicast-peers
no-cli
min-port=49152
max-port=49252
log-file=/var/log/turnserver.log
external-ip=${PUBLIC_IP}
realm=dev.panunkaergar.com
EOF

if [[ -f /etc/default/coturn ]]; then
  sed -i 's/^#*TURNSERVER_ENABLED=.*/TURNSERVER_ENABLED=1/' /etc/default/coturn
  grep -q '^TURNSERVER_ENABLED=1' /etc/default/coturn || echo 'TURNSERVER_ENABLED=1' >>/etc/default/coturn
fi

systemctl enable coturn
systemctl restart coturn
systemctl is-active --quiet coturn && echo "==> Coturn is running" || {
  echo "==> Coturn failed to start. Check: journalctl -u coturn -n 50"
  exit 1
}

if command -v ufw >/dev/null 2>&1 && ufw status | grep -q 'Status: active'; then
  ufw allow 3478/tcp
  ufw allow 3478/udp
  ufw allow 49152:49252/udp
  echo "==> UFW rules added for TURN"
else
  echo "==> NOTE: Open firewall UDP/TCP 3478 and UDP 49152-49252 if calls fail across networks."
fi

ENV_FILE="$LARAVEL_ROOT/.env"
touch "$ENV_FILE"

set_env() {
  local key="$1"
  local val="$2"
  if grep -q "^${key}=" "$ENV_FILE"; then
    sed -i "s|^${key}=.*|${key}=${val}|" "$ENV_FILE"
  else
    echo "${key}=${val}" >>"$ENV_FILE"
  fi
}

set_env "IN_APP_CALL_ENABLED" "true"
set_env "STUN_URL" "stun:stun.l.google.com:19302"
set_env "TURN_URL" "turn:${PUBLIC_IP}:3478"
set_env "TURN_USERNAME" "$TURN_USER"
set_env "TURN_CREDENTIAL" "$TURN_SECRET"

cd "$LARAVEL_ROOT"

PHP_BIN="$(command -v php || true)"
if [[ -z "$PHP_BIN" ]] && [[ -x /opt/alt/php83/usr/bin/php ]]; then
  PHP_BIN="/opt/alt/php83/usr/bin/php"
fi
if [[ -z "$PHP_BIN" ]]; then
  echo "Warning: php not found in PATH; run migrate and config:clear manually."
else
  echo "==> Running migrations and config clear..."
  "$PHP_BIN" artisan migrate --force --no-interaction 2>/dev/null || true
  "$PHP_BIN" artisan config:clear
  "$PHP_BIN" artisan cache:clear 2>/dev/null || true
fi

echo ""
echo "=============================================="
echo " TURN setup complete"
echo "=============================================="
echo " TURN_URL=turn:${PUBLIC_IP}:3478"
echo " TURN_USERNAME=${TURN_USER}"
echo " TURN_CREDENTIAL=${TURN_SECRET}"
echo " (also saved in ${ENV_FILE})"
echo ""
echo " Verify API ice_servers after login:"
echo "   GET /api/v1/customer/in-app-call/config"
echo "=============================================="
