<?php

namespace Modules\WhatsAppModule\Services;

use Modules\LeadManagement\Entities\AdSource;
use Modules\LeadManagement\Entities\CustomerLeadStatus;
use Modules\LeadManagement\Entities\Lead;
use Modules\LeadManagement\Services\LeadFollowupService;
use Modules\LeadManagement\Entities\LeadTypeHistory;
use Modules\LeadManagement\Entities\ProviderLeadStatus;
use Modules\LeadManagement\Entities\Source;
use Modules\UserManagement\Entities\User;
use Modules\WhatsAppModule\Entities\WhatsAppUser;
use Modules\WhatsAppModule\Support\SocialInboxChannel;

/**
 * CRM lead creation / typing for WhatsApp traffic (shared by internal API, webhooks, AI tools).
 */
class WhatsAppLeadLifecycleService
{
    /**
     * If the WhatsApp phone is already an onboarded provider-side user,
     * we should not create a new CRM Lead row for their inbound messages.
     */
    protected function isProviderAccountPhone(string $leadPhone): bool
    {
        return User::findByContactPhoneScoped($leadPhone, PROVIDER_USER_TYPES) !== null;
    }

    public function normalizeLeadPhone(?string $phone): ?string
    {
        if (!$phone) {
            return null;
        }

        if (SocialInboxChannel::current() !== SocialInboxChannel::WHATSAPP) {
            $t = preg_replace('/[^\w\-:+]+/', '', (string) $phone) ?? '';

            return $t !== '' ? substr($t, 0, 64) : null;
        }

        $digits = preg_replace('/\D+/', '', $phone) ?? '';
        if (strlen($digits) < 10) {
            return null;
        }

        return substr($digits, -10);
    }

    /**
     * Placeholder label auto-assigned when no real name is known (e.g. "WhatsApp 9353294014").
     */
    public static function isAutoGeneratedWhatsAppName(?string $name): bool
    {
        $trimmed = trim((string) $name);

        return $trimmed === '' || str_starts_with($trimmed, 'WhatsApp ');
    }

    /**
     * Return a usable customer name, or null when only a WhatsApp placeholder is available.
     */
    public static function realCustomerName(?string $name): ?string
    {
        $trimmed = trim((string) $name);
        if (self::isAutoGeneratedWhatsAppName($trimmed)) {
            return null;
        }

        return $trimmed;
    }

    protected function resolveWhatsAppUser(string $whatsAppPhone): ?WhatsAppUser
    {
        return WhatsAppUser::query()
            ->where('phone', $whatsAppPhone)
            ->where('channel', SocialInboxChannel::current())
            ->first();
    }

    protected function resolveSourceIdForWhatsAppPhone(string $whatsAppPhone): int
    {
        $waUser = $this->resolveWhatsAppUser($whatsAppPhone);

        if (app(WhatsAppCtwaAttributionService::class)->hasAdAttribution($waUser)) {
            return Source::ensureFacebookWhatsAppAdSource()->id;
        }

        return Source::ensureAiChatSource()->id;
    }

    /**
     * Map CTWA referral on the WhatsApp thread to CRM Ad Source (create if missing).
     */
    protected function resolveAdSourceIdForWhatsAppPhone(string $whatsAppPhone): ?int
    {
        $waUser = $this->resolveWhatsAppUser($whatsAppPhone);
        if (!app(WhatsAppCtwaAttributionService::class)->hasAdAttribution($waUser)) {
            return null;
        }

        $adSource = AdSource::ensureFromCtwaReferral(
            $waUser?->referral_source_id,
            $waUser?->referral_headline,
            $waUser?->referral_source_url,
            $waUser?->referral_source_type,
            $waUser?->referral_body
        );

        return $adSource?->id;
    }

    /**
     * Fill empty ad_source_id from CTWA attribution (does not overwrite staff-set values).
     */
    protected function applyCtwaAdSourceIfMissing(Lead $lead, ?string $whatsAppPhone): bool
    {
        if ($whatsAppPhone === null || $whatsAppPhone === '') {
            return false;
        }
        if ($lead->ad_source_id !== null) {
            return false;
        }
        $adSourceId = $this->resolveAdSourceIdForWhatsAppPhone($whatsAppPhone);
        if ($adSourceId === null) {
            return false;
        }
        $lead->ad_source_id = $adSourceId;

        return true;
    }

    public function ensureUnknownLeadForPhone(string $whatsAppPhone, ?string $name = null): ?Lead
    {
        $leadPhone = $this->normalizeLeadPhone($whatsAppPhone);
        if (!$leadPhone) {
            return null;
        }

        $existing = Lead::where('phone_number', $leadPhone)
            ->orderByDesc('id')
            ->get()
            ->first(fn (Lead $lead) => $this->isLeadOpen($lead));

        if ($existing) {
            return $this->touchAiOpenLead($existing, $name, $whatsAppPhone);
        }

        // Skip creation for already-onboarded providers.
        if ($this->isProviderAccountPhone($leadPhone)) {
            return null;
        }

        return Lead::create([
            'name' => trim((string) ($name ?: ('WhatsApp ' . $leadPhone))),
            'phone_number' => $leadPhone,
            'source_id' => $this->resolveSourceIdForWhatsAppPhone($whatsAppPhone),
            'ad_source_id' => $this->resolveAdSourceIdForWhatsAppPhone($whatsAppPhone),
            'lead_type' => Lead::TYPE_UNKNOWN,
            'date_time_of_lead_received' => now(),
            'handled_by' => 'AI',
            'created_by' => null,
            'next_followup_at' => app(LeadFollowupService::class)->defaultNextFollowupAt(),
        ]);
    }

    public function ensureLeadTypeForPhone(string $whatsAppPhone, string $leadType, ?string $name = null): ?Lead
    {
        $leadPhone = $this->normalizeLeadPhone($whatsAppPhone);
        if (!$leadPhone) {
            return null;
        }

        // 1) Reuse an already-open lead of the requested type (newest first).
        $sameTypeOpen = Lead::where('phone_number', $leadPhone)
            ->where('lead_type', $leadType)
            ->orderByDesc('id')
            ->get()
            ->first(fn (Lead $lead) => $this->isLeadOpen($lead));

        if ($sameTypeOpen) {
            return $this->touchAiOpenLead($sameTypeOpen, $name, $whatsAppPhone);
        }

        // 2) Upgrade the AI "unknown" thread lead in place — do not create a second row for the same chat.
        if (in_array($leadType, [Lead::TYPE_CUSTOMER, Lead::TYPE_PROVIDER], true)) {
            $unknownOpen = Lead::where('phone_number', $leadPhone)
                ->where('lead_type', Lead::TYPE_UNKNOWN)
                ->orderBy('id')
                ->get()
                ->first(fn (Lead $lead) => $this->isLeadOpen($lead));

            if ($unknownOpen) {
                return $this->convertUnknownOpenLeadToType($unknownOpen, $leadType, $name, $whatsAppPhone);
            }
        }

        // Skip creation for already-onboarded providers.
        if ($this->isProviderAccountPhone($leadPhone)) {
            return null;
        }

        $lead = Lead::create([
            'name' => trim((string) ($name ?: ('WhatsApp ' . $leadPhone))),
            'phone_number' => $leadPhone,
            'source_id' => $this->resolveSourceIdForWhatsAppPhone($whatsAppPhone),
            'ad_source_id' => $this->resolveAdSourceIdForWhatsAppPhone($whatsAppPhone),
            'lead_type' => $leadType,
            'date_time_of_lead_received' => now(),
            'handled_by' => 'AI',
            'created_by' => null,
            'next_followup_at' => app(LeadFollowupService::class)->defaultNextFollowupAt(),
        ]);
        $this->seedDefaultTypeHistoryForTypedLead($lead);
        $this->reportCtwaLeadSubmittedIfCustomer($whatsAppPhone, $lead);

        return $lead;
    }

    /**
     * Keep AI-handled fields fresh on an existing open lead.
     */
    protected function touchAiOpenLead(Lead $lead, ?string $name, ?string $whatsAppPhone = null): Lead
    {
        $dirty = false;
        if (empty($lead->handled_by)) {
            $lead->handled_by = 'AI';
            $dirty = true;
        }
        if ($lead->source_id === null) {
            $lead->source_id = $whatsAppPhone
                ? $this->resolveSourceIdForWhatsAppPhone($whatsAppPhone)
                : Source::ensureAiChatSource()->id;
            $dirty = true;
        } elseif ($whatsAppPhone) {
            $ctwaSourceId = Source::ensureFacebookWhatsAppAdSource()->id;
            $aiSourceId = Source::ensureAiChatSource()->id;
            if ((int) $lead->source_id === (int) $aiSourceId
                && (int) $this->resolveSourceIdForWhatsAppPhone($whatsAppPhone) === (int) $ctwaSourceId) {
                $lead->source_id = $ctwaSourceId;
                $dirty = true;
            }
        }
        if ($this->applyCtwaAdSourceIfMissing($lead, $whatsAppPhone)) {
            $dirty = true;
        }
        if ($name !== null && trim((string) $name) !== '') {
            $trimmed = trim((string) $name);
            $current = trim((string) ($lead->name ?? ''));
            if ($current === '' || str_starts_with($current, 'WhatsApp ')) {
                $lead->name = $trimmed;
                $dirty = true;
            }
        }
        if ($dirty) {
            $lead->save();
        }

        return $lead;
    }

    protected function convertUnknownOpenLeadToType(Lead $lead, string $newType, ?string $name, ?string $whatsAppPhone = null): Lead
    {
        $lead->lead_type = $newType;
        if ($name !== null && trim((string) $name) !== '') {
            $lead->name = trim((string) $name);
        }
        if (empty($lead->handled_by)) {
            $lead->handled_by = 'AI';
        }
        if ($lead->source_id === null || $whatsAppPhone) {
            $resolved = $whatsAppPhone
                ? $this->resolveSourceIdForWhatsAppPhone($whatsAppPhone)
                : Source::ensureAiChatSource()->id;
            $aiSourceId = Source::ensureAiChatSource()->id;
            if ($lead->source_id === null
                || ((int) $lead->source_id === (int) $aiSourceId && (int) $resolved !== (int) $aiSourceId)) {
                $lead->source_id = $resolved;
            }
        }
        $this->applyCtwaAdSourceIfMissing($lead, $whatsAppPhone);
        $lead->save();
        $this->seedDefaultTypeHistoryForTypedLead($lead);
        if ($whatsAppPhone) {
            $this->reportCtwaLeadSubmittedIfCustomer($whatsAppPhone, $lead);
        }

        return $lead->fresh();
    }

    protected function reportCtwaLeadSubmittedIfCustomer(string $whatsAppPhone, Lead $lead): void
    {
        if ($lead->lead_type !== Lead::TYPE_CUSTOMER) {
            return;
        }

        try {
            app(MetaConversionsApiService::class)->reportForPhone(
                $whatsAppPhone,
                MetaConversionsApiService::EVENT_LEAD_SUBMITTED,
                (int) $lead->id
            );
        } catch (\Throwable) {
            // Never block CRM on Meta CAPI failures.
        }
    }

    public function seedDefaultTypeHistoryForTypedLead(Lead $lead): void
    {
        if ($lead->lead_type === Lead::TYPE_CUSTOMER) {
            LeadTypeHistory::create([
                'lead_id' => $lead->id,
                'type' => Lead::TYPE_CUSTOMER,
                'data' => [
                    'customer_lead_status_id' => CustomerLeadStatus::defaultPendingStatusId(),
                    'booking_status' => 'pending',
                ],
                'created_by' => null,
            ]);
        } elseif ($lead->lead_type === Lead::TYPE_PROVIDER) {
            LeadTypeHistory::create([
                'lead_id' => $lead->id,
                'type' => Lead::TYPE_PROVIDER,
                'data' => [
                    'provider_lead_status_id' => ProviderLeadStatus::defaultPendingStatusId(),
                ],
                'created_by' => null,
            ]);
        }
    }

    public function isLeadOpen(Lead $lead): bool
    {
        if ($lead->lead_type === Lead::TYPE_UNKNOWN) {
            return true;
        }

        if (in_array($lead->lead_type, [Lead::TYPE_INVALID, Lead::TYPE_FUTURE_CUSTOMER], true)) {
            return false;
        }

        if ($lead->lead_type === Lead::TYPE_CUSTOMER) {
            $history = LeadTypeHistory::where('lead_id', $lead->id)
                ->where('type', Lead::TYPE_CUSTOMER)
                ->latest()
                ->first();
            $data = ($history && is_array($history->data)) ? $history->data : [];
            $statusId = $data['customer_lead_status_id'] ?? null;
            if (!$statusId) {
                return true;
            }
            $status = CustomerLeadStatus::find($statusId);
            $baseType = strtolower((string) ($status?->base_type ?? 'pending'));

            return !in_array($baseType, ['completed', 'cancel'], true);
        }

        if ($lead->lead_type === Lead::TYPE_PROVIDER) {
            $history = LeadTypeHistory::where('lead_id', $lead->id)
                ->where('type', Lead::TYPE_PROVIDER)
                ->latest()
                ->first();
            $data = ($history && is_array($history->data)) ? $history->data : [];
            $statusId = $data['provider_lead_status_id'] ?? null;
            if (!$statusId) {
                return true;
            }
            $status = ProviderLeadStatus::find($statusId);
            $baseType = strtolower((string) ($status?->base_type ?? 'pending'));

            return !in_array($baseType, ['completed', 'cancel'], true);
        }

        return false;
    }
}
